//region 1 = 19000048208
//region 2 = 19000048209
//region 3 = 19000048213
//region 4 = 19000048255
//region 5 = 19000050835
var created_at = {
    created_at: "created_at"
};

$(document).ready(function() {
    $('#testbutton').click(function () {
        $('#r1HideTicketsButton').hide();
        $('#r2HideTicketsButton').hide();
        $('#r3HideTicketsButton').hide();
        $('#r4HideTicketsButton').hide();
        $('#r5HideTicketsButton').hide();

        $('#r1OrdersDiv').hide();
        $('#r1QuoteDiv').hide();
        $('#r1ReordersDiv').hide();
        $('#r1ServicePartsDiv').hide();
        $('#r1ServiceRequestDiv').hide();
        $('#r1ChangeDiv').hide();
        $('#r1DiscountDiv').hide();
        $('#r1CreditDiv').hide();
        $('#r1ManufacturingDiv').hide();
        $('#r1MenardsDiv').hide();
        $('#r1CustomerInquiryDiv').hide();
        $('#r1WsosDiv').hide();
        $('#r1SocialMediaDiv').hide();
        $('#r1AlysDiv').hide();
        $('#r1TotalDiv').hide();
        $('#r1RushDiv').hide();
        $('#r1HelpdeskDiv').hide();
        $('#r1NoTagDiv').hide();
        $('#r2OrdersDiv').hide();
        $('#r2QuoteDiv').hide();
        $('#r2ReordersDiv').hide();
        $('#r2ServicePartsDiv').hide();
        $('#r2ServiceRequestDiv').hide();
        $('#r2ChangeDiv').hide();
        $('#r2DiscountDiv').hide();
        $('#r2CreditDiv').hide();
        $('#r2ManufacturingDiv').hide();
        $('#r2MenardsDiv').hide();
        $('#r2CustomerInquiryDiv').hide();
        $('#r2WsosDiv').hide();
        $('#r2SocialMediaDiv').hide();
        $('#r2AlysDiv').hide();
        $('#r2TotalDiv').hide();
        $('#r2RushDiv').hide();
        $('#r2HelpdeskDiv').hide();
        $('#r2NoTagDiv').hide();
        $('#r3OrdersDiv').hide();
        $('#r3QuoteDiv').hide();
        $('#r3ReordersDiv').hide();
        $('#r3ServicePartsDiv').hide();
        $('#r3ServiceRequestDiv').hide();
        $('#r3ChangeDiv').hide();
        $('#r3DiscountDiv').hide();
        $('#r3CreditDiv').hide();
        $('#r3ManufacturingDiv').hide();
        $('#r3MenardsDiv').hide();
        $('#r3CustomerInquiryDiv').hide();
        $('#r3WsosDiv').hide();
        $('#r3SocialMediaDiv').hide();
        $('#r3AlysDiv').hide();
        $('#r3TotalDiv').hide();
        $('#r3RushDiv').hide();
        $('#r3HelpdeskDiv').hide();
        $('#r3NoTagDiv').hide();
        $('#r4OrdersDiv').hide();
        $('#r4QuoteDiv').hide();
        $('#r4ReordersDiv').hide();
        $('#r4ServicePartsDiv').hide();
        $('#r4ServiceRequestDiv').hide();
        $('#r4ChangeDiv').hide();
        $('#r4DiscountDiv').hide();
        $('#r4CreditDiv').hide();
        $('#r4ManufacturingDiv').hide();
        $('#r4MenardsDiv').hide();
        $('#r4CustomerInquiryDiv').hide();
        $('#r4WsosDiv').hide();
        $('#r4SocialMediaDiv').hide();
        $('#r4AlysDiv').hide();
        $('#r4TotalDiv').hide();
        $('#r4RushDiv').hide();
        $('#r4HelpdeskDiv').hide();
        $('#r4NoTagDiv').hide();
        $('#r5OrdersDiv').hide();
        $('#r5QuoteDiv').hide();
        $('#r5ReordersDiv').hide();
        $('#r5ServicePartsDiv').hide();
        $('#r5ServiceRequestDiv').hide();
        $('#r5ChangeDiv').hide();
        $('#r5DiscountDiv').hide();
        $('#r5CreditDiv').hide();
        $('#r5ManufacturingDiv').hide();
        $('#r5MenardsDiv').hide();
        $('#r5CustomerInquiryDiv').hide();
        $('#r5WsosDiv').hide();
        $('#r5SocialMediaDiv').hide();
        $('#r5AlysDiv').hide();
        $('#r5TotalDiv').hide();
        $('#r5RushDiv').hide();
        $('#r5HelpdeskDiv').hide();
        $('#r5NoTagDiv').hide();
        $('#r1openQuotes').html("").css('color', 'white');
        $('#r1openOrders').html("").css('color', 'white');
        $('#r1openReorders').html("").css('color', 'white');
        $('#r1openServiceRequest').html("").css('color', 'white');
        $('#r1openServiceParts').html("").css('color', 'white');
        $('#r1openChange').html("").css('color', 'white');
        $('#r1openDiscount').html("").css('color', 'white');
        $('#r1openCredit').html("").css('color', 'white');
        $('#r1openManufacturing').html("").css('color', 'white');
        $('#r1openRush').html("").css('color', 'white');
        $('#r1openMenards').html("").css('color', 'white');
        $('#r1openCustomerInquiry').html("").css('color', 'white');
        $('#r1openHelpdesk').html("").css('color', 'white');
        $('#r1openWSOS').html("").css('color', 'white');
        $('#r1openSocialMedia').html("").css('color', 'white');
        $('#r1openAlys').html("").css('color', 'white');
        $('#r1openNoTag').html("").css('color', 'white');
        $('#r1allOpen').html("").css('color', 'white');
        $('#r2openQuotes').html("").css('color', 'white');
        $('#r2openOrders').html("").css('color', 'white');
        $('#r2openReorders').html("").css('color', 'white');
        $('#r2openServiceRequest').html("").css('color', 'white');
        $('#r2openServiceParts').html("").css('color', 'white');
        $('#r2openChange').html("").css('color', 'white');
        $('#r2openDiscount').html("").css('color', 'white');
        $('#r2openCredit').html("").css('color', 'white');
        $('#r2openManufacturing').html("").css('color', 'white');
        $('#r2openRush').html("").css('color', 'white');
        $('#r2openMenards').html("").css('color', 'white');
        $('#r2openCustomerInquiry').html("").css('color', 'white');
        $('#r2openHelpdesk').html("").css('color', 'white');
        $('#r2openWSOS').html("").css('color', 'white');
        $('#r2openSocialMedia').html("").css('color', 'white');
        $('#r2openAlys').html("").css('color', 'white');
        $('#r2openNoTag').html("").css('color', 'white');
        $('#r2allOpen').html("").css('color', 'white');
        $('#r3openQuotes').html("").css('color', 'white');
        $('#r3openOrders').html("").css('color', 'white');
        $('#r3openReorders').html("").css('color', 'white');
        $('#r3openServiceRequest').html("").css('color', 'white');
        $('#r3openServiceParts').html("").css('color', 'white');
        $('#r3openChange').html("").css('color', 'white');
        $('#r3openDiscount').html("").css('color', 'white');
        $('#r3openCredit').html("").css('color', 'white');
        $('#r3openManufacturing').html("").css('color', 'white');
        $('#r3openRush').html("").css('color', 'white');
        $('#r3openMenards').html("").css('color', 'white');
        $('#r3openCustomerInquiry').html("").css('color', 'white');
        $('#r3openHelpdesk').html("").css('color', 'white');
        $('#r3openWSOS').html("").css('color', 'white');
        $('#r3openSocialMedia').html("").css('color', 'white');
        $('#r3openAlys').html("").css('color', 'white');
        $('#r3openNoTag').html("").css('color', 'white');
        $('#r3allOpen').html("").css('color', 'white');
        $('#r4openQuotes').html("").css('color', 'white');
        $('#r4openOrders').html("").css('color', 'white');
        $('#r4openReorders').html("").css('color', 'white');
        $('#r4openServiceRequest').html("").css('color', 'white');
        $('#r4openServiceParts').html("").css('color', 'white');
        $('#r4openChange').html("").css('color', 'white');
        $('#r4openDiscount').html("").css('color', 'white');
        $('#r4openCredit').html("").css('color', 'white');
        $('#r4openManufacturing').html("").css('color', 'white');
        $('#r4openRush').html("").css('color', 'white');
        $('#r4openMenards').html("").css('color', 'white');
        $('#r4openCustomerInquiry').html("").css('color', 'white');
        $('#r4openHelpdesk').html("").css('color', 'white');
        $('#r4openWSOS').html("").css('color', 'white');
        $('#r4openSocialMedia').html("").css('color', 'white');
        $('#r4openAlys').html("").css('color', 'white');
        $('#r4openNoTag').html("").css('color', 'white');
        $('#r4allOpen').html("").css('color', 'white');
        $('#r5openQuotes').html("").css('color', 'white');
        $('#r5openOrders').html("").css('color', 'white');
        $('#r5openReorders').html("").css('color', 'white');
        $('#r5openServiceRequest').html("").css('color', 'white');
        $('#r5openServiceParts').html("").css('color', 'white');
        $('#r5openChange').html("").css('color', 'white');
        $('#r5openDiscount').html("").css('color', 'white');
        $('#r5openCredit').html("").css('color', 'white');
        $('#r5openManufacturing').html("").css('color', 'white');
        $('#r5openRush').html("").css('color', 'white');
        $('#r5openMenards').html("").css('color', 'white');
        $('#r5openCustomerInquiry').html("").css('color', 'white');
        $('#r5openHelpdesk').html("").css('color', 'white');
        $('#r5openWSOS').html("").css('color', 'white');
        $('#r5openSocialMedia').html("").css('color', 'white');
        $('#r5openAlys').html("").css('color', 'white');
        $('#r5openNoTag').html("").css('color', 'white');
        $('#r5allOpen').html("").css('color', 'white');
        $('#region1ContainerResolved').hide();
        $('#region1ContainerWorked').hide();
        $('#region2ContainerResolved').hide();
        $('#region2ContainerWorked').hide();
        $('#region3ContainerResolved').hide();
        $('#region3ContainerWorked').hide();
        $('#region4ContainerResolved').hide();
        $('#region4ContainerWorked').hide();
        $('#region5ContainerResolved').hide();
        $('#region5ContainerWorked').hide();
        $('#region1Container').hide();
        $('#region2Container').hide();
        $('#region3Container').hide();
        $('#region4Container').hide();
        $('#region5Container').hide();
        $('#region1Container').show();
        $('#region2Container').show();
        $('#region3Container').show();
        $('#region4Container').show();
        $('#region5Container').show();
        getPage1r1();
        getPage1r2();
        getPage1r3();
        getPage1r4();
        getPage1r5();
    });
});
